import { describe, expect, it } from 'vitest';
import vectors from '../vectors/qrst-sas.json' with { type: 'json' };
import { bytesToHex, commit, sasCode, sasDigits } from '../src/core/index.ts';

// The normative known answers of spec §6. These were generated by an implementation
// written separately from this one.
describe('§6 vectors', () => {
  const v = vectors;
  const transcript = {
    v: v.v,
    profile: v.profile,
    senderPub: v.snd_pubkey,
    receiverPub: v.rcv_pubkey,
    senderNonce: v.nonce_s,
    receiverNonce: v.nonce_r,
  };

  it('commit, Flow A (Sender contacts)', () => {
    expect(bytesToHex(commit(v.v, v.snd_pubkey, v.nonce_s))).toBe(v.commit_snd_contacting.commit);
  });

  it('commit, Flow B (Receiver contacts)', () => {
    expect(bytesToHex(commit(v.v, v.rcv_pubkey, v.nonce_r))).toBe(v.commit_rcv_contacting.commit);
  });

  it('code and digits', () => {
    const code = sasCode(transcript);
    expect(bytesToHex(code)).toBe(v.code);
    expect(sasDigits(code)).toBe(v.digits);
  });

  it('roles transposed gives the documented wrong answer, not the right one', () => {
    const wrong = sasCode({
      ...transcript,
      senderPub: v.rcv_pubkey,
      receiverPub: v.snd_pubkey,
      senderNonce: v.nonce_r,
      receiverNonce: v.nonce_s,
    });
    expect(bytesToHex(wrong)).toBe(v.code_with_roles_transposed.code);
    expect(bytesToHex(wrong)).not.toBe(v.code);
  });
});

describe('digits', () => {
  it('zero-pads to five', () => {
    expect(sasDigits(new Uint8Array([0, 0, 0, 0, 7]))).toBe('00007');
    expect(sasDigits(new Uint8Array([0, 0, 0, 0, 0]))).toBe('00000');
  });
  it('reduces a full 40-bit value without overflow', () => {
    // 0xffffffffff = 1099511627775; mod 100000 = 27775
    expect(sasDigits(new Uint8Array([255, 255, 255, 255, 255]))).toBe('27775');
    // 0x0100000000 = 4294967296; mod 100000 = 67296 — breaks an implementation using 32-bit shifts
    expect(sasDigits(new Uint8Array([1, 0, 0, 0, 0]))).toBe('67296');
  });
  it('depends on the profile and the version', () => {
    const base = {
      v: 1,
      profile: 'a',
      senderPub: '11'.repeat(32),
      receiverPub: '22'.repeat(32),
      senderNonce: '33'.repeat(32),
      receiverNonce: '44'.repeat(32),
    };
    const a = bytesToHex(sasCode(base));
    expect(bytesToHex(sasCode({ ...base, profile: 'b' }))).not.toBe(a);
    expect(bytesToHex(sasCode({ ...base, v: 2 }))).not.toBe(a);
  });
});
